// <auto-generated />
using System;
using Chris.Personnel.Management.EF.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chris.Personnel.Management.EF.Storage.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Chris.Personnel.Management.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnName("CardId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnName("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsEnabled")
                        .HasColumnName("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("Phone")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasColumnName("TrueName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ec1e37-fe6d-4606-902e-6705beb0afc0"),
                            CardId = "140226199401294051",
                            CreatedTime = new DateTime(2020, 7, 9, 23, 15, 14, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            IsEnabled = 1,
                            Name = "Admin",
                            Password = "D0988414729740502483CA8D031EC71EA9DDC0D41537B5995F63F88AE3DDE789",
                            Phone = "13259769759",
                            Salt = "2f460e1f-0193-4c5d-bed4-64b8a88d7f62",
                            TrueName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
