// <auto-generated />
using System;
using Chris.Personnel.Management.EF.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chris.Personnel.Management.EF.Storage.Migrations.Sqlite
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20200713011525_InitialSqliteDatabase")]
    partial class InitialSqliteDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Chris.Personnel.Management.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnName("CreatedUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnName("LastModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnName("LastModifiedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnName("Memo")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ec1e12-fe6d-4606-902e-6705beb0afc1"),
                            CreatedTime = new DateTime(2020, 7, 9, 23, 15, 14, 0, DateTimeKind.Unspecified),
                            CreatedUserId = new Guid("32ec1e37-fe6d-4606-902e-6705beb0afc0"),
                            IsDeleted = false,
                            Name = "管理员"
                        });
                });

            modelBuilder.Entity("Chris.Personnel.Management.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnName("CardId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnName("CreatedUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnName("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsEnabled")
                        .HasColumnName("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnName("LastModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifiedUserId")
                        .HasColumnName("LastModifiedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("Phone")
                        .HasColumnType("TEXT")
                        .HasMaxLength(11);

                    b.Property<Guid?>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasColumnName("TrueName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ec1e37-fe6d-4606-902e-6705beb0afc0"),
                            CardId = "140226199401294051",
                            CreatedTime = new DateTime(2020, 7, 9, 23, 15, 14, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            IsEnabled = 1,
                            Name = "Admin",
                            Password = "7C78A3031B38D8E22266DB5B0D2674DA18D625366238E0D5C551DC0B707638C7",
                            Phone = "13259769759",
                            RoleId = new Guid("32ec1e12-fe6d-4606-902e-6705beb0afc1"),
                            Salt = "842db147-6a5e-43e8-a166-55075c967b75",
                            TrueName = "Admin"
                        });
                });

            modelBuilder.Entity("Chris.Personnel.Management.Entity.User", b =>
                {
                    b.HasOne("Chris.Personnel.Management.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
